import type { DeviceAssessment } from '@/lib/deviceSurvey'

export interface PDFData {
  companyName:  string
  contactName:  string
  email:        string
  industry:     string
  /** Segmentation only — appears in the Audit Record, never in scored sections. */
  isLicensedBroadcaster?: string
  /** Device / RF pre-survey section — absent on submissions made before v2.0. */
  device?:      DeviceAssessment
  score:        number
  maxScore:     number
  riskLevel:    string
  riskBadge:    string
  analysis: {
    strengths:       string[]
    weaknesses:      string[]
    recommendations: string[]
  }
  auditRecord: {
    submissionDate: string
    surveyVersion:  string
    scoreGenerated: string
    responses: { question: string; answer: string; points: number; maxPoints?: number }[]
  }
}

type RGB = [number, number, number]

const NAVY:  RGB = [31,  41,  55]  // #1F2937 — Reports chrome
const BLUE:  RGB = [13, 148, 136]  // #0D9488 — Teal accent
const WHITE: RGB = [255, 255, 255]
const MUTED: RGB = [100, 116, 139]
const DARK:  RGB = [15,  23,  42]
const LIGHT: RGB = [248, 250, 252]  // #F8FAFC

const RISK_COLORS: Record<string, RGB> = {
  low:      [22,  163,  74],  // #16A34A
  moderate: [202, 138,   4],  // #CA8A04
  high:     [220,  38,  38],  // #DC2626
}

export async function generatePDF(data: PDFData): Promise<void> {
  const { jsPDF } = await import('jspdf')

  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const W    = 210
  const M    = 20
  const CW   = W - M * 2
  const rc   = RISK_COLORS[data.riskBadge] ?? RISK_COLORS.high
  const pct  = Math.round((data.score / data.maxScore) * 100)
  const date = new Date(data.auditRecord.submissionDate)
  const dateStr = date.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  // ── Helpers ──────────────────────────────────────────────────────────────

  // Page numbers are added in a final pass, once the total page count is known.
  function pageHeader(doc: InstanceType<typeof jsPDF>) {
    doc.setFillColor(...NAVY)
    doc.rect(0, 0, W, 16, 'F')
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text('AethyrLex  ·  FCC Compliance Readiness Assessment', M, 10)
  }

  function pageFooter(doc: InstanceType<typeof jsPDF>) {
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Generated by ComplianceIQ, an AethyrLex assessment  ·  ${dateStr}  ·  Confidential`,
      W / 2, 289, { align: 'center' },
    )
  }

  function sectionTitle(doc: InstanceType<typeof jsPDF>, text: string, y: number) {
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...DARK)
    doc.text(text, M, y)
    return y + 6
  }

  function paragraph(doc: InstanceType<typeof jsPDF>, text: string, y: number, maxW = CW) {
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines, M, y)
    return y + lines.length * 4.5
  }

  function bulletList(
    doc: InstanceType<typeof jsPDF>,
    items: string[],
    y: number,
    color: RGB,
  ): number {
    for (const item of items) {
      doc.setFillColor(...color)
      doc.circle(M + 1.5, y - 1.2, 1.5, 'F')
      const lines = doc.splitTextToSize(item, CW - 10)
      doc.setFontSize(9.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(51, 65, 85)
      doc.text(lines, M + 6, y)
      y += lines.length * 4.5 + 2
    }
    return y
  }

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover
  // ═══════════════════════════════════════════════════════════════════════

  doc.setFillColor(...NAVY)
  doc.rect(0, 0, W, 297, 'F')
  doc.setFillColor(...BLUE)
  doc.rect(0, 0, W, 4, 'F')

  // Logo
  doc.setFillColor(...BLUE)
  doc.roundedRect(M, 28, 26, 26, 3, 3, 'F')
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('IQ', M + 7.5, 45)

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('ComplianceIQ', M + 31, 37)
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('by AethyrLex  ·  FCC Compliance Assessment', M + 31, 44)

  doc.setDrawColor(255, 255, 255, 0.07)
  doc.setLineWidth(0.4)
  doc.line(M, 66, W - M, 66)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(45, 212, 191) // teal-300
  doc.text('FCC COMPLIANCE READINESS ASSESSMENT', W / 2, 82, { align: 'center' })

  doc.setFontSize(26)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  const nameLines = doc.splitTextToSize(data.companyName, CW)
  doc.text(nameLines, W / 2, 96, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text(dateStr, W / 2, 108 + (nameLines.length - 1) * 9, { align: 'center' })

  // Score
  const sy = 128 + (nameLines.length - 1) * 9
  doc.setFontSize(80)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(String(data.score), W / 2, sy + 42, { align: 'center' })
  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('out of 80 points', W / 2, sy + 52, { align: 'center' })

  // Risk badge
  const by = sy + 62
  doc.setFillColor(...rc)
  doc.roundedRect(W / 2 - 30, by, 60, 12, 3, 3, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(data.riskLevel.toUpperCase(), W / 2, by + 8, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text(`${pct}% compliance score`, W / 2, by + 20, { align: 'center' })

  doc.setDrawColor(255, 255, 255, 0.07)
  doc.line(M, by + 32, W - M, by + 32)

  doc.setFontSize(8.5)
  doc.setTextColor(...MUTED)
  doc.text(`Prepared for: ${data.contactName}  ·  ${data.email}`, W / 2, by + 42, { align: 'center' })
  doc.text(`Industry: ${data.industry}  ·  Survey v${data.auditRecord.surveyVersion}`, W / 2, by + 50, { align: 'center' })

  doc.setFontSize(7.5)
  doc.setTextColor(71, 85, 105)
  // Cover page number is added in the final pass

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 2 — Executive Summary
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc)

  let y = 30
  y = sectionTitle(doc, 'Executive Summary', y)
  y = paragraph(doc, `${data.companyName}  ·  ${dateStr}`, y) + 6

  // Score + Risk boxes
  doc.setFillColor(...WHITE)
  doc.roundedRect(M, y, 76, 42, 3, 3, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.35)
  doc.roundedRect(M, y, 76, 42, 3, 3, 'S')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MUTED)
  doc.text('COMPLIANCE SCORE', M + 38, y + 10, { align: 'center' })
  doc.setFontSize(30)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(String(data.score), M + 22, y + 30)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('/ 80', M + 42, y + 30)

  doc.setFillColor(...rc)
  doc.roundedRect(M + 82, y, 88, 42, 3, 3, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255, 0.75)
  doc.text('RISK LEVEL', M + 82 + 44, y + 10, { align: 'center' })
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(data.riskLevel, M + 82 + 44, y + 25, { align: 'center' })
  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'normal')
  doc.text(`${pct}% of maximum`, M + 82 + 44, y + 34, { align: 'center' })

  y += 50

  // Progress bar
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Score Distribution', M, y)
  y += 5
  doc.setFillColor(226, 232, 240)
  doc.roundedRect(M, y, CW, 5, 1.5, 1.5, 'F')
  doc.setFillColor(...rc)
  doc.roundedRect(M, y, (data.score / 80) * CW, 5, 1.5, 1.5, 'F')
  y += 12

  // Risk tier legend
  const tiers: [string, string, RGB][] = [
    ['Low Risk',      '65–80 pts', RISK_COLORS.low],
    ['Moderate Risk', '40–64 pts', RISK_COLORS.moderate],
    ['High Risk',     '0–39 pts',  RISK_COLORS.high],
  ]
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Risk Tiers', M, y)
  y += 5
  tiers.forEach(([label, range, color], i) => {
    const tx = M + i * 58
    doc.setFillColor(...color)
    doc.roundedRect(tx, y, 52, 12, 2, 2, 'F')
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text(label, tx + 26, y + 5.5, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.text(range, tx + 26, y + 10, { align: 'center' })
  })
  y += 22

  // AI analysis preview
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Compliance Analysis', M, y)
  y += 5
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('Scored against the AethyrLex 80-point framework  ·  AI-assisted interpretation of responses', M, y)
  y += 6

  const sections: [string, string[], RGB][] = [
    ['Strengths',       data.analysis.strengths,       RISK_COLORS.low],
    ['Weaknesses',      data.analysis.weaknesses,      RISK_COLORS.high],
    ['Recommendations', data.analysis.recommendations, BLUE],
  ]
  for (const [label, items, color] of sections) {
    if (y > 260) break
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...color)
    doc.text(`▸ ${label}`, M, y)
    y += 5
    y = bulletList(doc, items, y, color)
    y += 3
  }

  pageFooter(doc)

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 3 — Detailed Findings
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc)

  y = 30
  y = sectionTitle(doc, 'Detailed Findings', y)
  y = paragraph(doc, 'Individual question responses and RF risk areas with their compliance points.', y) + 4

  // Table header
  doc.setFillColor(...NAVY)
  doc.rect(M, y, CW, 9, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('#',         M + 3, y + 6)
  doc.text('Question',  M + 10, y + 6)
  doc.text('Response',  M + 120, y + 6)
  doc.text('Pts',       M + 148, y + 6)
  y += 9

  data.auditRecord.responses.forEach((r, i) => {
    const rowH = 12
    const bg: RGB = i % 2 === 0 ? WHITE : [241, 245, 249]
    doc.setFillColor(...bg)
    doc.rect(M, y, CW, rowH, 'F')
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.25)
    doc.line(M, y + rowH, M + CW, y + rowH)

    const max = r.maxPoints ?? 10   // submissions before v2.0 used 10 pts per question
    const ptColor: RGB = r.points >= max ? RISK_COLORS.low : r.points > 0 ? RISK_COLORS.moderate : RISK_COLORS.high

    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text(String(i + 1), M + 3, y + 8)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    const q = doc.splitTextToSize(r.question, 106)[0]
    doc.text(q, M + 10, y + 8)

    doc.setTextColor(...MUTED)
    const ans = r.answer.charAt(0).toUpperCase() + r.answer.slice(1)
    doc.text(ans, M + 120, y + 8)

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...ptColor)
    doc.text(`${r.points}/${max}`, M + 148, y + 8)

    doc.setFillColor(...ptColor)
    doc.circle(M + 164, y + 5.5, 2, 'F')

    y += rowH
  })

  // Total row
  y += 3
  const total = data.auditRecord.responses.reduce((s, r) => s + r.points, 0)
  doc.setFillColor(...NAVY)
  doc.roundedRect(M, y, CW, 11, 2, 2, 'F')
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('TOTAL COMPLIANCE SCORE', M + 10, y + 7.5)
  doc.setFillColor(...rc)
  doc.roundedRect(M + 136, y + 1.5, 38, 8, 2, 2, 'F')
  doc.text(`${total} / 80`, M + 155, y + 7.5, { align: 'center' })

  pageFooter(doc)

  // ═══════════════════════════════════════════════════════════════════════
  // Device RF Risk Assessment (may span several pages)
  // ═══════════════════════════════════════════════════════════════════════

  if (data.device) {
    const dev = data.device

    const newDevicePage = () => {
      doc.addPage()
      doc.setFillColor(...LIGHT)
      doc.rect(0, 0, W, 297, 'F')
      pageHeader(doc)
      pageFooter(doc)
      return 30
    }
    const ensure = (yy: number, h: number) => (yy + h > 275 ? newDevicePage() : yy)
    const text = (s: string, yy: number, opts: { x?: number; w?: number; size?: number; color?: RGB; bold?: boolean } = {}) => {
      const { x = M, w = CW, size = 9.5, color = [51, 65, 85] as RGB, bold = false } = opts
      doc.setFontSize(size)
      doc.setFont('helvetica', bold ? 'bold' : 'normal')
      doc.setTextColor(...color)
      const lh = size * 0.47
      for (const line of doc.splitTextToSize(s, w) as string[]) {
        yy = ensure(yy, lh)
        doc.text(line, x, yy)
        yy += lh
      }
      return yy
    }
    const subTitle = (s: string, yy: number) => text(s, ensure(yy, 12), { size: 11, bold: true, color: DARK }) + 2

    y = newDevicePage()
    y = sectionTitle(doc, 'Device RF Findings', y)
    y = paragraph(doc, 'Rule-based check for missing RF data, non-certified modules, multiple radios, unclear frequency bands and antenna modifications. These five areas make up 40 of the 80 points (see Detailed Findings).', y) + 3

    const counts = (['high', 'medium', 'low'] as const)
      .map(s => `${dev.flags.filter(f => f.severity === s).length} ${s}`).join('  ·  ')
    y = text(`Risks found: ${counts}`, y, { size: 9, bold: true, color: MUTED }) + 6

    y = subTitle('Likely Certification Path', y)
    y = text(dev.pathway, y) + 5

    if (dev.summary) {
      y = subTitle('Summary', y)
      y = text(dev.summary, y) + 5
    }

    y = subTitle(`Identified Risks (${dev.flags.length})`, y)
    if (!dev.flags.length) y = text('No RF risks identified from the information provided.', y) + 3
    for (const f of dev.flags) {
      y = ensure(y, 18)
      const c = RISK_COLORS[f.severity === 'medium' ? 'moderate' : f.severity] ?? MUTED
      doc.setFillColor(...(f.severity === 'low' ? MUTED : c))
      doc.roundedRect(M, y - 3.6, 15, 5, 1, 1, 'F')
      doc.setFontSize(6.5)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...WHITE)
      doc.text(f.severity.toUpperCase(), M + 7.5, y, { align: 'center' })
      y = text(f.title, y, { x: M + 18, w: CW - 18, bold: true, color: DARK })
      y = text(f.category.toUpperCase(), y + 0.5, { x: M + 18, w: CW - 18, size: 7, color: MUTED })
      y = text(f.detail, y + 0.5, { x: M + 18, w: CW - 18, size: 9 }) + 4
    }

    if (dev.missingInformation.length) {
      y = subTitle('Information to Gather', y + 2)
      for (const item of dev.missingInformation) {
        y = ensure(y, 6)
        doc.setFillColor(...RISK_COLORS.moderate)
        doc.circle(M + 1.5, y - 1.2, 1.2, 'F')
        y = text(item, y, { x: M + 6, w: CW - 6 }) + 2
      }
    }

    y = subTitle('Device Responses', y + 4)
    let currentModule = ''
    for (const r of dev.responses) {
      if (r.module !== currentModule) {
        currentModule = r.module
        y = ensure(y + 2, 12)
        doc.setFillColor(241, 245, 249)
        doc.rect(M, y - 4.5, CW, 7, 'F')
        y = text(currentModule.toUpperCase(), y, { x: M + 2, size: 8, bold: true, color: BLUE }) + 2.5
      }
      const qLines = doc.splitTextToSize(r.question, 78) as string[]
      const aLines = doc.splitTextToSize(r.answer, CW - 86) as string[]
      const h = Math.max(qLines.length, aLines.length) * 4.2 + 2.5
      y = ensure(y, h)
      doc.setFontSize(8.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(qLines, M + 2, y)
      doc.setTextColor(...DARK)
      doc.text(aLines, M + 86, y)
      y += h
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // LAST PAGE — Audit Record
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc)

  y = 30
  y = sectionTitle(doc, 'Audit Record', y)
  y = paragraph(doc, 'Submission metadata and certification trail.', y) + 4

  const auditRows: [string, string][] = [
    ['Submission Date',    data.auditRecord.scoreGenerated],
    ['Company Name',       data.companyName],
    ['Contact Name',       data.contactName],
    ['Email Address',      data.email],
    ['Industry',           data.industry],
    ['Licensed Broadcaster', data.isLicensedBroadcaster
                               ? data.isLicensedBroadcaster.charAt(0).toUpperCase() +
                                 data.isLicensedBroadcaster.slice(1).toLowerCase()
                               : 'Not provided'],
    ['Survey Version',     data.auditRecord.surveyVersion],
    ['Total Questions',    data.device ? '8 questions + 5 device modules' : '8'],
    ['Compliance Score',   `${data.score} / 80 points`],
    ['Risk Classification',data.riskLevel],
    ['Score Generated',    data.auditRecord.scoreGenerated],
  ]

  auditRows.forEach(([label, value], i) => {
    const rowH = 11
    const bg: RGB = i % 2 === 0 ? WHITE : [241, 245, 249]
    doc.setFillColor(...bg)
    doc.roundedRect(M, y, CW, rowH, 1, 1, 'F')
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.25)
    doc.roundedRect(M, y, CW, rowH, 1, 1, 'S')

    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text(label.toUpperCase(), M + 4, y + 7.5)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    doc.text(value, M + 80, y + 7.5)

    y += rowH
  })

  // Disclaimer
  y += 14
  doc.setFillColor(241, 245, 249)
  doc.roundedRect(M, y, CW, 38, 2, 2, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MUTED)
  doc.text('DISCLAIMER', M + 4, y + 8)
  doc.setFont('helvetica', 'normal')
  const disc = 'This report is generated based on self-reported responses and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified FCC regulatory counsel. AethyrLex makes no representations regarding the accuracy or completeness of this assessment.'
  const discLines = doc.splitTextToSize(disc, CW - 8)
  doc.text(discLines, M + 4, y + 15)

  pageFooter(doc)

  // ── Page numbers ─────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(i === 1 ? 7.5 : 8)
    if (i === 1) {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(71, 85, 105)
      doc.text(`Page 1 of ${pageCount}`, W / 2, 289, { align: 'center' })
    } else {
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...WHITE)
      doc.text(`Page ${i} of ${pageCount}`, W - M, 10, { align: 'right' })
    }
  }

  // ── Save ─────────────────────────────────────────────────────────────────
  const safe = data.companyName.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_')
  doc.save(`ComplianceIQ_${safe}_${date.getFullYear()}.pdf`)
}
