export interface PDFData {
  companyName:  string
  contactName:  string
  email:        string
  industry:     string
  score:        number
  maxScore:     number
  riskLevel:    string
  riskBadge:    string
  analysis: {
    strengths:       string[]
    weaknesses:      string[]
    recommendations: string[]
  }
  auditRecord: {
    submissionDate: string
    surveyVersion:  string
    scoreGenerated: string
    responses: { question: string; answer: string; points: number }[]
  }
}

type RGB = [number, number, number]

const NAVY:  RGB = [11,  22,  40]
const BLUE:  RGB = [26,  86, 219]
const WHITE: RGB = [255, 255, 255]
const MUTED: RGB = [100, 116, 139]
const DARK:  RGB = [15,  23,  42]
const LIGHT: RGB = [248, 250, 252]

const RISK_COLORS: Record<string, RGB> = {
  low:      [16,  185, 129],
  moderate: [245, 158,  11],
  high:     [239,  68,  68],
}

export async function generatePDF(data: PDFData): Promise<void> {
  const { jsPDF } = await import('jspdf')

  const doc  = new jsPDF({ unit: 'mm', format: 'a4' })
  const W    = 210
  const M    = 20
  const CW   = W - M * 2
  const rc   = RISK_COLORS[data.riskBadge] ?? RISK_COLORS.high
  const pct  = Math.round((data.score / data.maxScore) * 100)
  const date = new Date(data.auditRecord.submissionDate)
  const dateStr = date.toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  // ── Helpers ──────────────────────────────────────────────────────────────

  function pageHeader(doc: InstanceType<typeof jsPDF>, pageNum: number, total: number) {
    doc.setFillColor(...NAVY)
    doc.rect(0, 0, W, 16, 'F')
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text('ComplianceIQ  ·  FCC Compliance Readiness Assessment', M, 10)
    doc.text(`Page ${pageNum} of ${total}`, W - M, 10, { align: 'right' })
  }

  function pageFooter(doc: InstanceType<typeof jsPDF>) {
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(148, 163, 184)
    doc.text(
      `Generated by ComplianceIQ  ·  ${dateStr}  ·  Confidential`,
      W / 2, 289, { align: 'center' },
    )
  }

  function sectionTitle(doc: InstanceType<typeof jsPDF>, text: string, y: number) {
    doc.setFontSize(16)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...DARK)
    doc.text(text, M, y)
    return y + 6
  }

  function paragraph(doc: InstanceType<typeof jsPDF>, text: string, y: number, maxW = CW) {
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    const lines = doc.splitTextToSize(text, maxW)
    doc.text(lines, M, y)
    return y + lines.length * 4.5
  }

  function bulletList(
    doc: InstanceType<typeof jsPDF>,
    items: string[],
    y: number,
    color: RGB,
  ): number {
    for (const item of items) {
      doc.setFillColor(...color)
      doc.circle(M + 1.5, y - 1.2, 1.5, 'F')
      const lines = doc.splitTextToSize(item, CW - 10)
      doc.setFontSize(9.5)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(51, 65, 85)
      doc.text(lines, M + 6, y)
      y += lines.length * 4.5 + 2
    }
    return y
  }

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 1 — Cover
  // ═══════════════════════════════════════════════════════════════════════

  doc.setFillColor(...NAVY)
  doc.rect(0, 0, W, 297, 'F')
  doc.setFillColor(...BLUE)
  doc.rect(0, 0, W, 4, 'F')

  // Logo
  doc.setFillColor(26, 86, 219)
  doc.roundedRect(M, 28, 26, 26, 3, 3, 'F')
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('IQ', M + 7.5, 45)

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('ComplianceIQ', M + 31, 37)
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('FCC Compliance Assessment Platform', M + 31, 44)

  doc.setDrawColor(255, 255, 255, 0.07)
  doc.setLineWidth(0.4)
  doc.line(M, 66, W - M, 66)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(96, 165, 250)
  doc.text('FCC COMPLIANCE READINESS ASSESSMENT', W / 2, 82, { align: 'center' })

  doc.setFontSize(26)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  const nameLines = doc.splitTextToSize(data.companyName, CW)
  doc.text(nameLines, W / 2, 96, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text(dateStr, W / 2, 108 + (nameLines.length - 1) * 9, { align: 'center' })

  // Score
  const sy = 128 + (nameLines.length - 1) * 9
  doc.setFontSize(80)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(String(data.score), W / 2, sy + 42, { align: 'center' })
  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('out of 80 points', W / 2, sy + 52, { align: 'center' })

  // Risk badge
  const by = sy + 62
  doc.setFillColor(...rc)
  doc.roundedRect(W / 2 - 30, by, 60, 12, 3, 3, 'F')
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(data.riskLevel.toUpperCase(), W / 2, by + 8, { align: 'center' })

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text(`${pct}% compliance score`, W / 2, by + 20, { align: 'center' })

  doc.setDrawColor(255, 255, 255, 0.07)
  doc.line(M, by + 32, W - M, by + 32)

  doc.setFontSize(8.5)
  doc.setTextColor(...MUTED)
  doc.text(`Prepared for: ${data.contactName}  ·  ${data.email}`, W / 2, by + 42, { align: 'center' })
  doc.text(`Industry: ${data.industry}  ·  Survey v${data.auditRecord.surveyVersion}`, W / 2, by + 50, { align: 'center' })

  doc.setFontSize(7.5)
  doc.setTextColor(71, 85, 105)
  doc.text('Page 1 of 4', W / 2, 289, { align: 'center' })

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 2 — Executive Summary
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc, 2, 4)

  let y = 30
  y = sectionTitle(doc, 'Executive Summary', y)
  y = paragraph(doc, `${data.companyName}  ·  ${dateStr}`, y) + 6

  // Score + Risk boxes
  doc.setFillColor(...WHITE)
  doc.roundedRect(M, y, 76, 42, 3, 3, 'F')
  doc.setDrawColor(226, 232, 240)
  doc.setLineWidth(0.35)
  doc.roundedRect(M, y, 76, 42, 3, 3, 'S')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MUTED)
  doc.text('COMPLIANCE SCORE', M + 38, y + 10, { align: 'center' })
  doc.setFontSize(30)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(String(data.score), M + 22, y + 30)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...MUTED)
  doc.text('/ 80', M + 42, y + 30)

  doc.setFillColor(...rc)
  doc.roundedRect(M + 82, y, 88, 42, 3, 3, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255, 0.75)
  doc.text('RISK LEVEL', M + 82 + 44, y + 10, { align: 'center' })
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text(data.riskLevel, M + 82 + 44, y + 25, { align: 'center' })
  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'normal')
  doc.text(`${pct}% of maximum`, M + 82 + 44, y + 34, { align: 'center' })

  y += 50

  // Progress bar
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Score Distribution', M, y)
  y += 5
  doc.setFillColor(226, 232, 240)
  doc.roundedRect(M, y, CW, 5, 1.5, 1.5, 'F')
  doc.setFillColor(...rc)
  doc.roundedRect(M, y, (data.score / 80) * CW, 5, 1.5, 1.5, 'F')
  y += 12

  // Risk tier legend
  const tiers: [string, string, RGB][] = [
    ['Low Risk',      '65–80 pts', RISK_COLORS.low],
    ['Moderate Risk', '40–64 pts', RISK_COLORS.moderate],
    ['High Risk',     '0–39 pts',  RISK_COLORS.high],
  ]
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('Risk Tiers', M, y)
  y += 5
  tiers.forEach(([label, range, color], i) => {
    const tx = M + i * 58
    doc.setFillColor(...color)
    doc.roundedRect(tx, y, 52, 12, 2, 2, 'F')
    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text(label, tx + 26, y + 5.5, { align: 'center' })
    doc.setFont('helvetica', 'normal')
    doc.text(range, tx + 26, y + 10, { align: 'center' })
  })
  y += 22

  // AI analysis preview
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text('AI-Generated Analysis', M, y)
  y += 8

  const sections: [string, string[], RGB][] = [
    ['Strengths',       data.analysis.strengths,       RISK_COLORS.low],
    ['Weaknesses',      data.analysis.weaknesses,      RISK_COLORS.high],
    ['Recommendations', data.analysis.recommendations, BLUE],
  ]
  for (const [label, items, color] of sections) {
    if (y > 260) break
    doc.setFontSize(9.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...color)
    doc.text(`▸ ${label}`, M, y)
    y += 5
    y = bulletList(doc, items, y, color)
    y += 3
  }

  pageFooter(doc)

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 3 — Detailed Findings
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc, 3, 4)

  y = 30
  y = sectionTitle(doc, 'Detailed Findings', y)
  y = paragraph(doc, 'Individual question responses and associated compliance points.', y) + 4

  // Table header
  doc.setFillColor(...NAVY)
  doc.rect(M, y, CW, 9, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('#',         M + 3, y + 6)
  doc.text('Question',  M + 10, y + 6)
  doc.text('Response',  M + 120, y + 6)
  doc.text('Pts',       M + 148, y + 6)
  y += 9

  data.auditRecord.responses.forEach((r, i) => {
    const rowH = 12
    const bg: RGB = i % 2 === 0 ? WHITE : [241, 245, 249]
    doc.setFillColor(...bg)
    doc.rect(M, y, CW, rowH, 'F')
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.25)
    doc.line(M, y + rowH, M + CW, y + rowH)

    const ptColor: RGB = r.points === 10 ? RISK_COLORS.low : r.points === 5 ? RISK_COLORS.moderate : RISK_COLORS.high

    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text(String(i + 1), M + 3, y + 8)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    const q = doc.splitTextToSize(r.question, 106)[0]
    doc.text(q, M + 10, y + 8)

    doc.setTextColor(...MUTED)
    const ans = r.answer.charAt(0).toUpperCase() + r.answer.slice(1)
    doc.text(ans, M + 120, y + 8)

    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...ptColor)
    doc.text(`${r.points}/10`, M + 148, y + 8)

    doc.setFillColor(...ptColor)
    doc.circle(M + 164, y + 5.5, 2, 'F')

    y += rowH
  })

  // Total row
  y += 3
  const total = data.auditRecord.responses.reduce((s, r) => s + r.points, 0)
  doc.setFillColor(...NAVY)
  doc.roundedRect(M, y, CW, 11, 2, 2, 'F')
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...WHITE)
  doc.text('TOTAL COMPLIANCE SCORE', M + 10, y + 7.5)
  doc.setFillColor(...rc)
  doc.roundedRect(M + 136, y + 1.5, 38, 8, 2, 2, 'F')
  doc.text(`${total} / 80`, M + 155, y + 7.5, { align: 'center' })

  pageFooter(doc)

  // ═══════════════════════════════════════════════════════════════════════
  // PAGE 4 — Audit Record
  // ═══════════════════════════════════════════════════════════════════════

  doc.addPage()
  doc.setFillColor(...LIGHT)
  doc.rect(0, 0, W, 297, 'F')
  pageHeader(doc, 4, 4)

  y = 30
  y = sectionTitle(doc, 'Audit Record', y)
  y = paragraph(doc, 'Submission metadata and certification trail.', y) + 4

  const auditRows: [string, string][] = [
    ['Submission Date',    data.auditRecord.scoreGenerated],
    ['Company Name',       data.companyName],
    ['Contact Name',       data.contactName],
    ['Email Address',      data.email],
    ['Industry',           data.industry],
    ['Survey Version',     data.auditRecord.surveyVersion],
    ['Total Questions',    '8'],
    ['Compliance Score',   `${data.score} / 80 points`],
    ['Risk Classification',data.riskLevel],
    ['Score Generated',    data.auditRecord.scoreGenerated],
  ]

  auditRows.forEach(([label, value], i) => {
    const rowH = 11
    const bg: RGB = i % 2 === 0 ? WHITE : [241, 245, 249]
    doc.setFillColor(...bg)
    doc.roundedRect(M, y, CW, rowH, 1, 1, 'F')
    doc.setDrawColor(226, 232, 240)
    doc.setLineWidth(0.25)
    doc.roundedRect(M, y, CW, rowH, 1, 1, 'S')

    doc.setFontSize(7.5)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...MUTED)
    doc.text(label.toUpperCase(), M + 4, y + 7.5)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    doc.text(value, M + 80, y + 7.5)

    y += rowH
  })

  // Disclaimer
  y += 14
  doc.setFillColor(241, 245, 249)
  doc.roundedRect(M, y, CW, 38, 2, 2, 'F')
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...MUTED)
  doc.text('DISCLAIMER', M + 4, y + 8)
  doc.setFont('helvetica', 'normal')
  const disc = 'This report is generated based on self-reported responses and is for informational purposes only. It does not constitute legal advice and should not replace consultation with qualified FCC regulatory counsel. ComplianceIQ makes no representations regarding the accuracy or completeness of this assessment.'
  const discLines = doc.splitTextToSize(disc, CW - 8)
  doc.text(discLines, M + 4, y + 15)

  pageFooter(doc)

  // ── Save ─────────────────────────────────────────────────────────────────
  const safe = data.companyName.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_')
  doc.save(`ComplianceIQ_${safe}_${date.getFullYear()}.pdf`)
}
